<?php

namespace Database\Seeders;

use App\Models\Blockchain;
use Illuminate\Database\Seeder;

class BlockchainSeeder extends Seeder
{
    public function run(): void
    {
        $blockchains = [
            // Layer 1 Blockchains
            [
                'name' => 'Ethereum',
                'slug' => 'ethereum',
                'symbol' => 'ETH',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/ethereum.svg',
                'description' => 'The world\'s programmable blockchain',
                'rpc_url' => 'https://eth-mainnet.g.alchemy.com/v2/demo',
                'explorer_url' => 'https://etherscan.io',
                'chain_id' => 1,
                'priority' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'Bitcoin',
                'slug' => 'bitcoin',
                'symbol' => 'BTC',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/bitcoin.svg',
                'description' => 'The first and most secure blockchain',
                'explorer_url' => 'https://blockchain.com',
                'priority' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'BNB Smart Chain',
                'slug' => 'bsc',
                'symbol' => 'BNB',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/bnb.svg',
                'description' => 'High-performance blockchain for DeFi',
                'rpc_url' => 'https://bsc-dataseed.binance.org',
                'explorer_url' => 'https://bscscan.com',
                'chain_id' => 56,
                'priority' => 95,
                'is_active' => true,
            ],
            [
                'name' => 'Solana',
                'slug' => 'solana',
                'symbol' => 'SOL',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/solana.svg',
                'description' => 'High-speed blockchain for DeFi and NFTs',
                'rpc_url' => 'https://api.mainnet-beta.solana.com',
                'explorer_url' => 'https://solscan.io',
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Polygon',
                'slug' => 'polygon',
                'symbol' => 'MATIC',
                'type' => 'layer2',
                'logo_url' => '/images/blockchains/polygon.svg',
                'description' => 'Ethereum scaling solution',
                'rpc_url' => 'https://polygon-rpc.com',
                'explorer_url' => 'https://polygonscan.com',
                'chain_id' => 137,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Avalanche',
                'slug' => 'avalanche',
                'symbol' => 'AVAX',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/avalanche.svg',
                'description' => 'Fast, low-cost blockchain platform',
                'rpc_url' => 'https://api.avax.network/ext/bc/C/rpc',
                'explorer_url' => 'https://snowtrace.io',
                'chain_id' => 43114,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Arbitrum',
                'slug' => 'arbitrum',
                'symbol' => 'ARB',
                'type' => 'layer2',
                'logo_url' => '/images/blockchains/arbitrum.svg',
                'description' => 'Ethereum Layer 2 scaling solution',
                'rpc_url' => 'https://arb1.arbitrum.io/rpc',
                'explorer_url' => 'https://arbiscan.io',
                'chain_id' => 42161,
                'priority' => 75,
                'is_active' => true,
            ],
            [
                'name' => 'Optimism',
                'slug' => 'optimism',
                'symbol' => 'OP',
                'type' => 'layer2',
                'logo_url' => '/images/blockchains/optimism.svg',
                'description' => 'Ethereum Layer 2 with low fees',
                'rpc_url' => 'https://mainnet.optimism.io',
                'explorer_url' => 'https://optimistic.etherscan.io',
                'chain_id' => 10,
                'priority' => 70,
                'is_active' => true,
            ],
            [
                'name' => 'Base',
                'slug' => 'base',
                'symbol' => 'ETH',
                'type' => 'layer2',
                'logo_url' => '/images/blockchains/base.svg',
                'description' => 'Coinbase Layer 2 on Ethereum',
                'rpc_url' => 'https://mainnet.base.org',
                'explorer_url' => 'https://basescan.org',
                'chain_id' => 8453,
                'priority' => 65,
                'is_active' => true,
            ],
            [
                'name' => 'Cardano',
                'slug' => 'cardano',
                'symbol' => 'ADA',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/cardano.svg',
                'description' => 'Proof-of-stake blockchain platform',
                'explorer_url' => 'https://cardanoscan.io',
                'priority' => 60,
                'is_active' => true,
            ],
            [
                'name' => 'Polkadot',
                'slug' => 'polkadot',
                'symbol' => 'DOT',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/polkadot.svg',
                'description' => 'Multi-chain blockchain platform',
                'explorer_url' => 'https://polkadot.subscan.io',
                'priority' => 55,
                'is_active' => true,
            ],
            [
                'name' => 'Cosmos',
                'slug' => 'cosmos',
                'symbol' => 'ATOM',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/cosmos.svg',
                'description' => 'Internet of blockchains',
                'explorer_url' => 'https://www.mintscan.io',
                'priority' => 50,
                'is_active' => true,
            ],
            [
                'name' => 'Near Protocol',
                'slug' => 'near',
                'symbol' => 'NEAR',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/near.svg',
                'description' => 'Sharded proof-of-stake blockchain',
                'rpc_url' => 'https://rpc.mainnet.near.org',
                'explorer_url' => 'https://nearblocks.io',
                'priority' => 45,
                'is_active' => true,
            ],
            [
                'name' => 'Aptos',
                'slug' => 'aptos',
                'symbol' => 'APT',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/aptos.svg',
                'description' => 'Scalable Layer 1 blockchain',
                'rpc_url' => 'https://fullnode.mainnet.aptoslabs.com/v1',
                'explorer_url' => 'https://explorer.aptoslabs.com',
                'priority' => 40,
                'is_active' => true,
            ],
            [
                'name' => 'Sui',
                'slug' => 'sui',
                'symbol' => 'SUI',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/sui.svg',
                'description' => 'High-performance Layer 1 blockchain',
                'rpc_url' => 'https://fullnode.mainnet.sui.io',
                'explorer_url' => 'https://suiscan.xyz',
                'priority' => 35,
                'is_active' => true,
            ],
            [
                'name' => 'zkSync Era',
                'slug' => 'zksync',
                'symbol' => 'ETH',
                'type' => 'layer2',
                'logo_url' => '/images/blockchains/zksync.svg',
                'description' => 'Zero-knowledge rollup on Ethereum',
                'rpc_url' => 'https://mainnet.era.zksync.io',
                'explorer_url' => 'https://explorer.zksync.io',
                'chain_id' => 324,
                'priority' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'Fantom',
                'slug' => 'fantom',
                'symbol' => 'FTM',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/fantom.svg',
                'description' => 'Fast, scalable blockchain platform',
                'rpc_url' => 'https://rpc.ftm.tools',
                'explorer_url' => 'https://ftmscan.com',
                'chain_id' => 250,
                'priority' => 25,
                'is_active' => true,
            ],
            [
                'name' => 'Cronos',
                'slug' => 'cronos',
                'symbol' => 'CRO',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/cronos.svg',
                'description' => 'Crypto.com blockchain',
                'rpc_url' => 'https://evm.cronos.org',
                'explorer_url' => 'https://cronoscan.com',
                'chain_id' => 25,
                'priority' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'Tron',
                'slug' => 'tron',
                'symbol' => 'TRX',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/tron.svg',
                'description' => 'Decentralized blockchain platform',
                'explorer_url' => 'https://tronscan.org',
                'priority' => 15,
                'is_active' => true,
            ],
            [
                'name' => 'Litecoin',
                'slug' => 'litecoin',
                'symbol' => 'LTC',
                'type' => 'layer1',
                'logo_url' => '/images/blockchains/litecoin.svg',
                'description' => 'Peer-to-peer cryptocurrency',
                'explorer_url' => 'https://blockchair.com/litecoin',
                'priority' => 10,
                'is_active' => true,
            ],
        ];

        foreach ($blockchains as $blockchain) {
            Blockchain::create($blockchain);
        }
    }
}
