<?php

namespace Database\Seeders;

use App\Models\PaymentGateway;
use Illuminate\Database\Seeder;

class PaymentGatewaySeeder extends Seeder
{
    public function run(): void
    {
        $gateways = [
            // International - Fiat
            [
                'name' => 'Stripe',
                'slug' => 'stripe',
                'type' => 'fiat',
                'description' => 'Accept credit cards, debit cards, and digital wallets',
                'logo_url' => '/images/gateways/stripe.svg',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'SEK', 'NOK', 'DKK'],
                'supported_methods' => ['card', 'bank_transfer', 'wallet'],
                'supported_countries' => ['US', 'GB', 'CA', 'AU', 'EU', 'JP', 'SG'],
                'transaction_fee_percent' => 2.9,
                'transaction_fee_fixed' => 0.30,
                'priority' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'PayPal',
                'slug' => 'paypal',
                'type' => 'fiat',
                'description' => 'Accept PayPal, credit cards, and debit cards',
                'logo_url' => '/images/gateways/paypal.svg',
                'supported_currencies' => ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'],
                'supported_methods' => ['paypal', 'card'],
                'supported_countries' => ['US', 'GB', 'CA', 'AU', 'EU', 'JP'],
                'transaction_fee_percent' => 3.49,
                'transaction_fee_fixed' => 0.49,
                'priority' => 90,
                'is_active' => true,
            ],
            
            // India - Fiat
            [
                'name' => 'Razorpay',
                'slug' => 'razorpay',
                'type' => 'fiat',
                'description' => 'Accept UPI, cards, netbanking, and wallets in India',
                'logo_url' => '/images/gateways/razorpay.svg',
                'supported_currencies' => ['INR'],
                'supported_methods' => ['upi', 'card', 'netbanking', 'wallet'],
                'supported_countries' => ['IN'],
                'transaction_fee_percent' => 2.0,
                'transaction_fee_fixed' => 0,
                'priority' => 95,
                'is_active' => true,
            ],
            [
                'name' => 'Paytm',
                'slug' => 'paytm',
                'type' => 'fiat',
                'description' => 'Accept Paytm wallet, UPI, and cards',
                'logo_url' => '/images/gateways/paytm.svg',
                'supported_currencies' => ['INR'],
                'supported_methods' => ['wallet', 'upi', 'card'],
                'supported_countries' => ['IN'],
                'transaction_fee_percent' => 1.99,
                'transaction_fee_fixed' => 0,
                'priority' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'PhonePe',
                'slug' => 'phonepe',
                'type' => 'fiat',
                'description' => 'Accept PhonePe wallet and UPI payments',
                'logo_url' => '/images/gateways/phonepe.svg',
                'supported_currencies' => ['INR'],
                'supported_methods' => ['wallet', 'upi'],
                'supported_countries' => ['IN'],
                'transaction_fee_percent' => 1.5,
                'transaction_fee_fixed' => 0,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Cashfree',
                'slug' => 'cashfree',
                'type' => 'fiat',
                'description' => 'Accept UPI, cards, netbanking, and wallets',
                'logo_url' => '/images/gateways/cashfree.svg',
                'supported_currencies' => ['INR'],
                'supported_methods' => ['upi', 'card', 'netbanking', 'wallet'],
                'supported_countries' => ['IN'],
                'transaction_fee_percent' => 1.95,
                'transaction_fee_fixed' => 0,
                'priority' => 75,
                'is_active' => true,
            ],
            [
                'name' => 'Instamojo',
                'slug' => 'instamojo',
                'type' => 'fiat',
                'description' => 'Accept cards, UPI, netbanking, and wallets',
                'logo_url' => '/images/gateways/instamojo.svg',
                'supported_currencies' => ['INR'],
                'supported_methods' => ['card', 'upi', 'netbanking', 'wallet'],
                'supported_countries' => ['IN'],
                'transaction_fee_percent' => 2.0,
                'transaction_fee_fixed' => 3,
                'priority' => 70,
                'is_active' => true,
            ],
            
            // Crypto Gateways
            [
                'name' => 'Coinbase Commerce',
                'slug' => 'coinbase-commerce',
                'type' => 'crypto',
                'description' => 'Accept Bitcoin, Ethereum, and other cryptocurrencies',
                'logo_url' => '/images/gateways/coinbase.svg',
                'supported_currencies' => ['BTC', 'ETH', 'USDC', 'USDT', 'DAI'],
                'supported_methods' => ['crypto'],
                'supported_countries' => ['*'],
                'transaction_fee_percent' => 1.0,
                'transaction_fee_fixed' => 0,
                'priority' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'Cryptomus',
                'slug' => 'cryptomus',
                'type' => 'crypto',
                'description' => 'Low-fee crypto payment gateway',
                'logo_url' => '/images/gateways/cryptomus.svg',
                'supported_currencies' => ['BTC', 'ETH', 'USDT', 'USDC', 'BNB', 'TRX', 'LTC'],
                'supported_methods' => ['crypto'],
                'supported_countries' => ['*'],
                'transaction_fee_percent' => 0.5,
                'transaction_fee_fixed' => 0,
                'priority' => 95,
                'is_active' => true,
            ],
            [
                'name' => 'NOWPayments',
                'slug' => 'nowpayments',
                'type' => 'crypto',
                'description' => 'Accept 300+ cryptocurrencies',
                'logo_url' => '/images/gateways/nowpayments.svg',
                'supported_currencies' => ['BTC', 'ETH', 'USDT', 'USDC', 'BNB', 'XRP', 'ADA', 'SOL', 'DOGE', 'MATIC'],
                'supported_methods' => ['crypto'],
                'supported_countries' => ['*'],
                'transaction_fee_percent' => 0.5,
                'transaction_fee_fixed' => 0,
                'priority' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'CoinPayments',
                'slug' => 'coinpayments',
                'type' => 'crypto',
                'description' => 'Accept Bitcoin and 2000+ altcoins',
                'logo_url' => '/images/gateways/coinpayments.svg',
                'supported_currencies' => ['BTC', 'ETH', 'LTC', 'BCH', 'DOGE', 'XRP'],
                'supported_methods' => ['crypto'],
                'supported_countries' => ['*'],
                'transaction_fee_percent' => 0.5,
                'transaction_fee_fixed' => 0,
                'priority' => 85,
                'is_active' => true,
            ],
            
            // Regional
            [
                'name' => 'Mollie',
                'slug' => 'mollie',
                'type' => 'fiat',
                'description' => 'European payment methods (iDEAL, SEPA, etc.)',
                'logo_url' => '/images/gateways/mollie.svg',
                'supported_currencies' => ['EUR', 'GBP', 'USD'],
                'supported_methods' => ['ideal', 'sepa', 'card', 'bancontact'],
                'supported_countries' => ['NL', 'BE', 'DE', 'FR', 'GB'],
                'transaction_fee_percent' => 1.8,
                'transaction_fee_fixed' => 0.25,
                'priority' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Mercado Pago',
                'slug' => 'mercado-pago',
                'type' => 'fiat',
                'description' => 'Latin America payment gateway',
                'logo_url' => '/images/gateways/mercadopago.svg',
                'supported_currencies' => ['BRL', 'MXN', 'ARS', 'CLP'],
                'supported_methods' => ['card', 'bank_transfer', 'cash'],
                'supported_countries' => ['BR', 'MX', 'AR', 'CL'],
                'transaction_fee_percent' => 3.99,
                'transaction_fee_fixed' => 0,
                'priority' => 75,
                'is_active' => true,
            ],
        ];

        foreach ($gateways as $gateway) {
            PaymentGateway::create($gateway);
        }
    }
}
